//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalleKonv01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public Nullable<int> Auto1 { get; set; }
        public int Auto2 { get; set; }
        public Nullable<short> Sesson { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public float Placering { get; set; }
        public Nullable<short> Spil1_spillet { get; set; }
        public float Spil1 { get; set; }
        public Nullable<short> Spil2_spillet { get; set; }
        public Nullable<float> Spil2 { get; set; }
        public Nullable<short> Spil3_spillet { get; set; }
        public Nullable<float> Spil3 { get; set; }
        public Nullable<short> Spil4_spillet { get; set; }
        public Nullable<float> Spil4 { get; set; }
        public Nullable<short> Spil5_spillet { get; set; }
        public Nullable<float> Spil5 { get; set; }
        public Nullable<float> Gennemsnit { get; set; }
        public bool Kamel_passer { get; set; }
    }
}
