//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalleKonv01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stam
    {
        public int Stam_Auto1 { get; set; }
        public string Stam_Navn { get; set; }
        public string Stam_init { get; set; }
        public Nullable<System.DateTime> Stam_Opt_dato { get; set; }
        public bool Stam_Formand { get; set; }
        public bool Stam_Nastformand { get; set; }
        public bool Stam_Kasser { get; set; }
        public bool Stam_Revisor { get; set; }
        public bool Stam_Skema_ansvarlig { get; set; }
        public bool Stam_Web { get; set; }
        public bool Stam_Aktiv_medlem { get; set; }
        public bool Stam_Aresmedlem { get; set; }
        public bool Stam_Provemedlem { get; set; }
        public bool Stam_Passiv { get; set; }
        public bool Stam_Udmeldt { get; set; }
        public Nullable<System.DateTime> Stam_Udmeldt_dato { get; set; }
        public string Stam_E_Mail { get; set; }
    }
}
